Repository ramy-att/trivial-soen341project2023, pull requests merged in 2023-03, with the labels that each got.

#77 Update database.txt
  database.txt
Labels: documentation

#91 PDF Upload
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/components/Postings/Posting.js
  package-lock.json
  package.json
  server/controller/file-controller.js
  server/controller/student-controller.js
  server/controller/uploads/coverLetters/640bed07ba4b4ab648528f29.pdf
  server/controller/uploads/resumes/640bed07ba4b4ab648528f29.pdf
  server/controller/uploads/transcripts/640bed07ba4b4ab648528f29.pdf
  server/index.js
  server/routes/file-routes.js
  server/upload.html
Labels: Feature

#112 107 employer to create posting for backend and delete postings if needed
  client/src/components/Postings/EmployerPostings.js
  client/src/components/Postings/ManagePosting.js
  client/src/components/Postings/Posting.js
  package-lock.json
Labels: Feature, Sprint 3

#127 Student application
  client/src/components/Postings/Posting.js
Labels: Feature

#128 126 update database.txt for the database and server
  database.txt
Labels: documentation

#135 Routes
  client/package-lock.json
  client/src/App.js
  client/src/components/Application/Application.js
  client/src/components/NavBar/OurNav.js
  client/src/components/Postings/EditPosting.js
  client/src/components/Postings/EmployerPostings.js
  client/src/components/Postings/ManagePosting.js
  client/src/components/Postings/Posting.js
  client/src/components/SignIn/SignIn.js
  client/src/pages/ApplicationsPage.js
  client/src/pages/HomePage.js
  client/src/pages/PostingsPage.js
  client/src/pages/SignInPage.js
  client/src/pages/SignUpPageEmp.js
  client/src/pages/SignUpPageStu.js
Labels: bug

#134 Block reapplying and fixed CSS for status
  client/src/components/Postings/Posting.js
  client/src/components/Postings/Postings.css
  server/controller/application-controller.js
  server/controller/uploads/coverLetters/641d14d26649fc8ac2e1db20.pdf
  server/controller/uploads/resumes/641d14d26649fc8ac2e1db20.pdf
  server/controller/uploads/transcripts/641d14d26649fc8ac2e1db20.pdf
  server/routes/application-routes.js
Labels: Feature
